# config.py - CLAVES CENTRALIZADAS (FINAL)

# --- 1. SPOTIFY ---
CLIENT_ID="TU_CLIENT_ID_AQUI"
CLIENT_SECRET="TU_CLIENT_SECRET_AQUI"

LASTFM_KEY="TU_LASTFM_KEY_AQUI"

# --- 3. YOUTUBE (NUEVA CLAVE) ---
YOUTUBE_KEY="TU_YOUTUBE_KEY_AQUI"
